=== DanielFloresLopez/sewDef/xml/rutas.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns="http://tempuri.org/rutas" elementFormDefault="qualified" targetNamespace="http://tempuri.org/rutas" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="rutas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="ruta" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ruta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombreruta" />
				<xs:element ref="tiporuta" />
				<xs:element ref="agencia" />
				<xs:element ref="descripcion" />
				<xs:element ref="recomendacionpersonas" />
				<xs:element ref="lugarinicio" />
				<xs:element ref="referencias" />
				<xs:element ref="recomendacion" />
				<xs:element ref="hitos" />
			</xs:sequence>
			<xs:attribute name="fechainicio" type="xs:date" />
			<xs:attribute name="horainicio" type="xs:time" />
			<xs:attribute name="tiemporuta" type="xs:duration" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombreruta" type="xs:string" />
	<xs:element name="tiporuta">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="transporte" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="agencia" type="xs:string" />
	<xs:element name="descripcion" type="xs:string" />
	<xs:element name="recomendacionpersonas" type="xs:string" />
	<xs:element name="lugarinicio">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="direccion" type="xs:string" use="required" />
					<xs:attribute name="longitud" use="required" >
						<xs:simpleType>
							<xs:restriction base="xs:decimal">
								<xs:minInclusive value="-180.0"/>
								<xs:maxInclusive value="180.0"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="latitud" use="required" >
						<xs:simpleType>
							<xs:restriction base="xs:decimal">
								<xs:minInclusive value="-90.0"/>
								<xs:maxInclusive value="90.0"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="altitud" type="xs:decimal" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="recomendacion">
		<xs:simpleType>
			<xs:restriction base="xs:int">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="10"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>	
	<xs:element name="hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombrehito" />
				<xs:element ref="descripcionhito" />
				<xs:element ref="fotografias" />
				<xs:element ref="videos" />
			</xs:sequence>
			<xs:attribute name="longitud" type="xs:NMTOKEN" use="required" />
			<xs:attribute name="latitud" type="xs:NMTOKEN" use="required" />
			<xs:attribute name="altitud" type="xs:NMTOKEN" use="required" />
			<xs:attribute name="distanciahito" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="nombrehito" type="xs:string" />
	<xs:element name="descripcionhito" type="xs:string" />
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia" type="xs:string" />
	<xs:element name="video" type="xs:string" />
</xs:schema>

=== DanielFloresLopez/sewDef/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas xsi:schemaLocation="http://www.uniovi.es/rutas rutas.xsd" xmlns="http://www.uniovi.es/rutas" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:null="http://www.uniovi.es/rutas">
    <ruta fechainicio="2023-12-02" horainicio="10:00:00" tiemporuta="PT2H42M">
        <nombreruta> Hargeisa Route</nombreruta>
        <tiporuta transporte="a pie"> Tour de la ciudad </tiporuta>
        <agencia>Sin agencia</agencia>
        <descripcion>Ruta de un paseo por Hargeisa, una de las ciudades más importantes de Somalia.
        </descripcion>
        <recomendacionpersonas> Perfecta para todas las edades</recomendacionpersonas>
        <lugarinicio direccion="H3Q7+FR3, Hargeisa, Somalia" longitud="9.588680851619683" latitud="44.064539980140495" altitud="1260">Hargeisa City Stadium</lugarinicio>
        <referencias>
            <referencia>
                https://es.wikipedia.org/wiki/Hargeisa
            </referencia>
            <referencia>
                https://es.wikipedia.org/wiki/Somalilandia
            </referencia>
            <referencia>
                https://moys.govsomaliland.org/article/stadium
            </referencia>
        </referencias>
        <recomendacion>6</recomendacion>
        <hitos>
            <hito longitud="9.58259714321547" latitud="44.099562162081114" altitud="1281" distanciahito="7" tipodistancia="km" nombrehito="Nassa Hablood Park">
                <descripcionhito> Parque reconocido como lugar histórico de la ciudad de Hargeisa</descripcionhito>
                <fotografias>
                    <fotografia>fotografia1.jpg</fotografia>
                </fotografias>
                <videos></videos>
            </hito>
            <hito longitud="9.56081850772289" latitud="44.08721752883517" altitud="1267" distanciahito="5" tipodistancia="km" nombrehito="Maamus Hotel Hargeisa">
                <descripcionhito> Hotel con las mejores valoraciones de la ciudad</descripcionhito>
                <fotografias>
                    <fotografia>fotografia1.jpg</fotografia>
                </fotografias>
                <videos></videos>
            </hito>
            <hito longitud="9.561464573397487" latitud="44.08097796379248" altitud="1261" distanciahito="1" tipodistancia="km" nombrehito="BEERTA LIBAAXA RESTUARANTE CAFE">
                <descripcionhito> Restaurante considerado una gran atracción turística de la ciudad de Hargeisa</descripcionhito>
                <fotografias>
                    <fotografia>fotografia1.jpg</fotografia>
                </fotografias>
                <videos></videos>
            </hito>
        </hitos>
    </ruta>
    <ruta fechainicio="2023-12-15" horainicio="18:00:00" tiemporuta="PT1H14M">
        <nombreruta> Visita a los monumentos de Mogadiscio</nombreruta>
        <tiporuta transporte="a pie"> Tour de la ciudad</tiporuta>
        <agencia>Sin agencia</agencia>
        <descripcion>Ruta por la capital de Somalia que visita aquellos monumentos alejados de la costa, pero con un gran interés para el país.</descripcion>
        <recomendacionpersonas> Perfecta para todas las edades</recomendacionpersonas>
        <lugarinicio direccion="Estadio Mogadiscio" longitud="2.067611485529539" latitud="45.33521678837033" altitud="74">Muqdisho Stadium</lugarinicio>
        <referencias>
            <referencia>
                https://es.wikipedia.org/wiki/Universidad_de_Mogadiscio
            </referencia>
            <referencia>
                https://www.tripadvisor.es/Attraction_Review-g294440-d13153963-Reviews-Mogadishu_Stadium-Mogadishu.html
            </referencia>
            <referencia>
                https://elpais.com/noticias/mogadiscio/
            </referencia>
        </referencias>
        <recomendacion>8</recomendacion>
        <hitos>
            <hito longitud="2.062272809495288" latitud="45.320945692464896" altitud="71" distanciahito="2" tipodistancia="km" nombrehito="University of Somalia">
                <descripcionhito> Universidad única de Mogadiscio, junto a la Somali international university.</descripcionhito>
                <fotografias>
                    <fotografia>fotografia1.jpg</fotografia>
                </fotografias>
                <videos></videos>
            </hito>
            <hito longitud="2.061432072275904" latitud="45.32017380047232" altitud="73" distanciahito="1" tipodistancia="km" nombrehito="Somali international university">
                <descripcionhito> Es una de las universidades más importantes de toda Somalia</descripcionhito>
                <fotografias>
                    <fotografia>fotografia1.jpg</fotografia>
                </fotografias>
                <videos></videos>
            </hito>
            <hito longitud="2.054386485118926" latitud="45.29555203248958" altitud="91" distanciahito="3" tipodistancia="km" nombrehito="Cinema baariyow">
                <descripcionhito> Cine más famoso de la ciudad de Mogadiscio</descripcionhito>
                <fotografias>
                    <fotografia>fotografia1.jpg</fotografia>
                </fotografias>
                <videos></videos>
            </hito>
        </hitos>
    </ruta>
    <ruta fechainicio="2023-12-20" horainicio="10:00:00" tiemporuta="PT2H2M">
        <nombreruta> Visita por la costa de Mogadiscio</nombreruta>
        <tiporuta transporte="a pie"> Ruta por la ciudad</tiporuta>
        <agencia>Sin agencia</agencia>
        <descripcion>Ruta por las playas de Mogadiscio, las más turísticas de toda Somalia, además de ver algunos de los monumentos más importantes, como su faro, uno de los más antiguos en funcionamiento.</descripcion>
        <recomendacionpersonas> Perfecta para todas las edades</recomendacionpersonas>
        <lugarinicio direccion="273V+9C, Mogadishu, Somalia" longitud="2.0029472721305885" latitud="45.29336070090095" altitud="3">AAIA beach</lugarinicio>
        <referencias>
            <referencia>
                https://es.wikipedia.org/wiki/Aeropuerto_Internacional_Aden_Adde
            </referencia>
            <referencia>
                https://www.archdaily.com.br/br/893050/estudantes-de-arquitetura-da-somalia-preservam-digitalmente-o-patrimonio-construido-de-seu-pais-antes-que-seja-tarde-demais
            </referencia>
            <referencia>
                https://www.alamy.es/foto-las-personas-se-reunen-en-la-tumba-del-soldado-desconocido-en-la-capital-de-somalia-mogadiscio-para-celebrar-el-eid-al-fitr-el-28-de-julio-amisom-foto-tobin-jones-115369821.html
            </referencia>
        </referencias>
        <recomendacion>9</recomendacion>
        <hitos>
            <hito longitud="2.017988503081041" latitud="45.303862120448635" altitud="16" distanciahito="3" tipodistancia="km" nombrehito="Aden Adde">
                <descripcionhito> Aeropuerto Internacional Aden Adde</descripcionhito>
                <fotografias>
                    <fotografia>fotografia1.jpg</fotografia>
                </fotografias>
                <videos></videos>
            </hito>
            <hito longitud="2.033703008940806" latitud="45.34382395155846" altitud="1" distanciahito="5" tipodistancia="km" nombrehito="Lighthouse of Mogadiscio">
                <descripcionhito> Faro de Mogadiscio que sigue operativo y tiene una visita entre las 6 de la mañana y las 6 de la tarde.</descripcionhito>
                <fotografias>
                    <fotografia>fotografia1.jpg</fotografia>
                </fotografias>
                <videos></videos>
            </hito>
            <hito longitud="2.039120298996535" latitud="45.34191447930742" altitud="15" distanciahito="1" tipodistancia="km" nombrehito="The Tomb of the Unknown Soldier">
                <descripcionhito> Daljirka Dahsoon es un monumento a la Tumba del Soldado Desconocido ubicado en Mogadiscio. El monumento fue erigido en honor a los hombres y mujeres somalíes que murieron en defensa de la República de Somalia.</descripcionhito>
                <fotografias>
                    <fotografia>fotografia1.jpg</fotografia>
                </fotografias>
                <videos></videos>
            </hito>
        </hitos>
    </ruta>
</rutas>
